
all:
	$gcc -w filters.c -o ../bin/filters
	$gcc -w GrayToBin.c -o ../bin/GrayToBin
	$gcc -w IntensityGray.c -o ../bin/IntensityGray
	$gcc -w IntensityRGB.c -o ../bin/IntensityRGB
	$gcc -w GrayToBin.c -o ../bin/GrayToBin
	$gcc -w RGBToGray.c -o ../bin/RGBToGray
	$gcc -w waterMarker.c -o ../bin/waterMarker


